// Module included in the following assemblies:
// * rosa-release-notes.adoc

:_mod-docs-content-type: REFERENCE
[id="rosa-q4-2025_{context}"]
= Q4 2025

ifdef::openshift-rosa-hcp[]
* **Platform monitoring using the Cluster Monitoring Operator.** You can now configure the in-cluster monitoring stack components, metrics, and alerts to monitor both core platform components and user-defined projects. Previously, you could only monitor user-defined projects. This change applies to both new and existing {product-title} clusters. However, it affects them differently.
+
** For new clusters created after this change, the default, in-cluster monitoring stack is installed during cluster installation and immediately begins collecting metrics. After installation, you can use the default configuration, or you can modify the monitoring components to suit your needs.
** For existing clusters created prior to this change, no changes will be made to the cluster's monitoring configuration. However, you can begin to use the core platform monitoring components, and modify them to suit your needs.
+
For more information, see link:https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws/4/html-single/monitoring/index[Monitoring].
endif::openshift-rosa-hcp[]

* **New version of {product-title} available.** {product-title} version 4.20 is now available for new clusters.

ifdef::openshift-rosa-hcp[]
* ** On-Demand Capacity Reservations and Capacity Blocks for ML now supported.** You can now use pre-purchased Capacity Reservations when creating new machine pools on {product-title} clusters. For more information, see link:https://docs.redhat.com/documentation/red_hat_openshift_service_on_aws/4/html-single/cluster_administration/index#rosa-managing-worker-nodes[Managing compute nodes].

* ** ImageDigestMirrorSets (IDMS) now supported.**
{product-title} now supports ImageDigestMirrorSets (IDMS), enabling clusters to redirect image pulls to a private, mirrored registry. This critical enhancement means customers in air-gapped or restricted networks can host their own mirrors for third-party images while satisfying strict security and compliance requirements. For more information, see link:https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws/4/html-single/images/index#images-registry-mirroring_image-configuration-hcp[Image registry mirroring for {product-title}].

* **{product-title} regions added.** {product-title} is now available in the following regions:
+
** Mexico (`mx-central-1`)
** Thailand (`ap-southeast-7`)
+
For more information on region availabilities, see link:https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws/4/html-single/introduction_to_rosa/index#rosa-sdpolicy-regions-az_rosa-hcp-service-definition[Regions and availability zones].
endif::openshift-rosa-hcp[]